apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: docker.io/caddy
          ports:
            - containerPort: 80