services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    
    api:
        build: 
             context: ./
             dockerfile: Dockerfile
        image: docker.io/vinaydt1/simple_blog_api
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
        ports:
            - "3000:3000"