use office;
DROP TABLE dialogue;
DROP TABLE Dialogue_Final;
CREATE TABLE dialogue (Name STRING,Dialogues STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INPATH '/root/Inputs/episodeIV_dialogues.txt' INTO TABLE dialogue;
LOAD DATA LOCAL INPATH '/root/Inputs/episodeV_dialogues.txt' INTO TABLE dialogue;
LOAD DATA LOCAL INPATH '/root/Inputs/episodeVI_dialogues.txt' INTO TABLE dialogue;
CREATE TABLE Dialogue_Final AS SELECT Name,No_Of_Dialogues FROM(SELECT Name,COUNT(1) as No_Of_Dialogues FROM dialogue GROUP BY Name)w ORDER by No_Of_Dialogues DESC;
INSERT OVERWRITE DIRECTORY 'hdfs:///user/root/vinay/pig_project/Hive_Project1' ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' SELECT * FROM Dialogue_Final;
