DROP TABLE LUKE_Counter;

-- Creating Table
CREATE TABLE LUKE_Counter (name STRING, line STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");

-- Loading data into the table
LOAD DATA LOCAL INPATH 'root/episodeIV_dialogues.txt' INTO TABLE LUKE_Counter;

-- Generate output and export it
INSERT OVERWRITE LOCAL DIRECTORY 'root/LukeCounter'
SELECT COUNT(*) FROM LUKE_Counter where INSTR(line, 'Luke')>0;
