services:
    redis-server:
        image: docker.io/redis
        volumes:
          - ./redis:/data
        command: ["redis-server", "--save", "1 1","--protected-mode", "no"]
    node-app:
        build: ./
        image: docker.io/vinaydt1/visits
        ports:
            - "8081:8081"