# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'Automatically Reject PRs'
on:
  pull_request_target:
    types:
      - opened
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "We don't accept PRs against this repo. Make sure you only push to your forks."
